version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASS}
    restart: always
    volumes:
      - skap_api_pgdata:/var/lib/postgresql/data

  api: &api
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["bundle", "exec", "puma", "-C", "config/puma.rb"]
    ports:
      - "80:3000"
    environment: &rails_environment
      RAILS_ENV: production
      DBHOST: postgres
      ANYCABLE_HTTP_BROADCAST_URL: http://ws:8090/_broadcast
    restart: always
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_started
      anycable:
        condition: service_started
  
  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api

  anycable:
    <<: *api
    command: bundle exec anycable
    environment:
      <<: *rails_environment
      ANYCABLE_RPC_HOST: 0.0.0.0:50051
    ports:
      - '50051'
    restart: always
    depends_on:
      ws:
        condition: service_started

  ws:
    image: anycable/anycable-go:1.5
    ports:
      - '8080:8080'
      - '8090'
    restart: always
    environment:
      ANYCABLE_HOST: "0.0.0.0"
      ANYCABLE_BROADCAST_ADAPTER: http
      ANYCABLE_RPC_HOST: anycable:50051
      ANYCABLE_DEBUG: ${ANYCABLE_DEBUG:-true}

volumes:
  skap_api_pgdata:
